services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
    extra_hosts:
      - "pi8-1.local:10.15.8.225"
      - "k8s-81.local:10.15.8.81"
    restart: always
